### ISSUE TITLE
Failed to resolve import "./item.svelte" from "node_modules/svantic/src/views/item/index.js". Does the file exist?

### ISSUE THREAD

**Issue by VirgileD** [ryu-man/svantic#2]
Hello, after having installed SvelteKit demo app, I tried to install svantic by simply npm install svantic. Then I add a button directly in the __layout.js to test and got the error of the title of this issue.
I noticed that indeed item.svelte does not exist as it's written Item.svelte with an uppercase "i". It's the only file in the directory that has its first letter in uppercase so I suppose it's a mistake.
Renaming the file to item.svelte seems to do the trick.

**Comment by ibilux** [comment]
Are you using (linux, mac) or windows ?
This https://github.com/ryu-man/svantic/pull/3/commits/a0f99452a25cfffc520fd6a87d4d8bd539a0d342 should fix this.
